name: ci-docs

on:
  workflow_dispatch:
  push:
     paths:
      - 'docs/**' 
    # branches:
    #   - main
      

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

  install-dependencies:
    runs-on: ubuntu-latest

    steps:
      - name: Build and Start
        run: yarn start

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Build and Start
        run: yarn start
